### ISSUE TITLE
Support for IPv6 and dual-stack

### ISSUE THREAD

**Issue by uablrek** [k8snetworkplumbingwg/multus-service#1]
Issue for tracking. Only IPv4 works.

**Comment by s1061123** [comment]
Thank you for your feedback @uablrek

As you mentioned, multus-service is not supoprted IPv6 yet, but before IPv6, IPv4 implementation is not perfect yet.
Currently we are planning to implement IPv6 but it is not near future, more far future feature.
IPv4 hardening is the first topic, in addition, we need to discuss how to implement IPv6 service (incl. dual-stack) in NPWG.

Hence I close it for now and I move this topic in TODO in readme.
Design proposal is welcome in NPWG!

**Comment by abasitt** [comment]
@s1061123 is there any more progress on this ? I checked and IPv6 is still not working and I also can't find anything in the TODO in README.
