### ISSUE TITLE
does it work across different macvlans?

### ISSUE THREAD

**Issue by yifeng-cerebras** [k8snetworkplumbingwg/multus-service#10]
I have two nodes of different NICs where one node is using macvlan1 and the other is using macvlan2.

Building the svc with the same macvlan will work, but if I create a client pod with macvlan1 and another pod/svc with macvlan2, then client pod won't be able to connect with cluster ip or svc name (directly connect with pod macvlan ips will work though).

Can anyone educate me if it's supported yet or some direction where I can look into?
Thanks

**Comment by yifeng-cerebras** [comment]
solved by myself, if anyone has the same requirement, it's [due to this one](https://github.com/k8snetworkplumbingwg/multus-service/blob/3a731ef41a1b7d6778f85503eced2b19d72d1bdf/pkg/proxy/server/server.go#L478)
basically if you do have the need to add iptables/routing of all svc to one NIC, you'll need to update here

**Comment by s1061123** [comment]
Hi @yifeng-cerebras 

As you conclude it, multus-service gives to access a service if the pod belongs to the network of the service. This is because we expect that service should be access through target net-attach-def. If the pod does not belongs to the net-attach-def, then it should NOT be accessible because the pod does not have a path to the service.

**Comment by yifeng-cerebras** [comment]
Hi @s1061123,

Thanks for the education and I agree in general they should not be accessible across different net-attach-def.

However, my use case is NIC names are different and macvlan has to specify the NIC name in net-attach-def so I have to use different net-attach-def but the NICs are actually connected and accessible to each other.

So I think it's a valid case and others may have similar cases so it might be helpful to support with additional flags.
