### ISSUE TITLE
Multus proxy keep crashing

### ISSUE THREAD

**Issue by rsidhaarth** [k8snetworkplumbingwg/multus-service#31]
Multus proxy service keeps restarting every minute. And the logs says

```
E0423 20:21:26.983615       1 pod.go:373] failed to get cri client: failed to connect: failed to connect to unix:///host/run/crio/crio.sock, make sure you are running as root and the runtime has been started: context deadline exceeded
F0423 20:21:26.984069       1 main.go:65] cannot create pod change tracker
```

**Comment by s1061123** [comment]
> It is now pretty early stage of development, hence everything may be changed without any notification. Please do NOT use it as production. We don't support any question about how-to-use/how-to-deploy until current development status is changed.

As of above (described in README.md), let me close this issue. From the error message, your multus proxy cannot connect to container runtime. Please check your container runtime configuration and change that (which is in muluus-proxy deployment in `deploy.yml` file).
